# Generated by Django 5.2.4 on 2025-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
