# Generated by Django 5.2.4 on 2025-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_roomimage_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
