# Generated by Django 5.2.4 on 2025-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_roomimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
