# Generated by Django 5.2.4 on 2025-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='security_level',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(default=500, help_text='Size in square feet'),
        ),
    ]
