# Generated by Django 5.2.4 on 2025-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_alter_menuitem_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
